import { useState } from "react";
import Head from "next/head";

export default function Home() {
  const [currentUrl, setCurrentUrl] = useState("");
  const [inputValue, setInputValue] = useState(
    "http://localhost:3000/accounts/login"
  );

  return (
    <>
      <Head>
        <title>iFrame tester</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: "flex", gap: "24px", marginBottom: "30px" }}>
          <input
            type="text"
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
          />
          <button
            onClick={() => setCurrentUrl(inputValue)}
            style={{ width: "40px" }}
          >
            Go
          </button>
        </div>
        <iframe src={currentUrl} title="test" height="900px" width="100%" />
      </main>
    </>
  );
}
